// <auto-generated />
using System;
using Kys.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Kys.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608140000_Sprint11_FixKbVisibilityColumn")]
    partial class Sprint11_FixKbVisibilityColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
