// <auto-generated />
using System;
using System.Collections.Generic;
using Kys.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kys.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608120000_Sprint11_SeedResourceTypes")]
    partial class Sprint11_SeedResourceTypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
